---
name: How2Do
version: 1.0.1
main: CodeGhost\How2Do\Main
api: 4.0.0

commands:
 lb:
  description: Leaderboard Command
  permission: lb.command.cmd
 
 money:
  description: Money Command
  permission: lb.money.cmd

permissions:
  lb.command.cmd:
    description: "Allows the user to run leaderboard Command"
    default: op
  
  lb.money.cmd:
      description: "Allows the user to run money command"
      default: op
...
